### ISSUE TITLE
Indicate whether Backloader is enabled using the browser-action icon

### ISSUE THREAD

**Issue by Nateowami** [Nateowami/Backloader#14]
I often find (especially with the newer more aggressive filter) that pages don't load right, and I forget that Backloader is on or off. It can work both ways, where I get "This page has been blocked by an extension" and quickly know to turn it off, or the more subtle problem of pages not loading right because it's off (because it had previously been causing trouble on).

My suggestion is to make the browser-action icon grayscale when it's off, or else use the hand-drawn logo (I'm partial to the latter suggestion because it's more original, and I kinda like the hand-drawn version).

As always I'm just putting this here so it's on the radar screen. I don't have immediate plans to address it.

**Comment by JoshTheDerf** [comment]
@Nateowami Good idea! I don't still have the hand-drawn icon, mind sending it? I think this shouldn't be too much trouble. Might have some time today to work on it.

**Comment by Nateowami** [comment]
I agree; this shouldn't be hard. The hand-drawn logo is in the repo: https://github.com/Nateowami/Backloader/blob/c71462340b309cb105ee1f02cace4114151bc2d2/icon.png

**Comment by JoshTheDerf** [comment]
Oyea. Thanks.

**Comment by JoshTheDerf** [comment]
Initial support in https://github.com/Tribex/Backloader/tree/enabled-icon.
I think maybe a grayscale icon might look better, especially since we're limited to png images of 19px and 38px in size.

**Comment by Nateowami** [comment]
The image can't be scaled? But it doesn't matter, let's just go with garyscale.

**Comment by JoshTheDerf** [comment]
@Nateowami Nope, it only accepts 19 and 38 for that size. (Or imageData, but I don't think we want to go there, and that defaults to 19.) Larger images get scaled down and look horrid.

EDIT: Updated branch to use the grayscale normal icon.
Did you want _gray_scale or _gary_scale? Who's Gary? What sort of scale does he have? :P

**Comment by Nateowami** [comment]
Does it look horrid if it gets scaled manually first? Let's just go with grayscale though.

Gary would like to blame Chromium's spellcheck for not having grayscale (and therefore making it necessary to ignore spellcheck for that word).

**Comment by JoshTheDerf** [comment]
@Nateowami No, scaling manually looks fine. Not sure why it can scale large images well from the manifest, but not from the API.

Poor Gary. :(
