### ISSUE TITLE
Weird error in v0.2.0

### ISSUE THREAD

**Issue by Nateowami** [Nateowami/Backloader#15]
Naturally an inexplicable error I've never seen before began as soon as I released v0.2.0. I _thought_ there weren't any errors... Everything seemed to be working right, and I thought I would have noticed if errors were logged.

Apparently the regression began in ae4e301f5a7691a952560d94a82d3246ac2f8725, with `filterList` becoming undefined. This gets logged twice:

```
Error in event handler for webRequest.onBeforeRequest/8: TypeError: Cannot read property 'length' of undefined
    at manageRequest (chrome-extension://jmmkjkhlifgcjopifeplcamfmndgibge/scripts/background/background.js:93:31)handler @ extensions::uncaught_exception_handler:8
```

The really weird thing though, is that that commit is really simple and has _nothing_ to do with `filterList`.

**Comment by Nateowami** [comment]
I found the issue and fixed it in e9250dc5a6aa60af5a64d5e185d9d805a7804e36. The problem was that Backloader was trying to decide what to do with a request before it had finished starting up, and while `filterList` was undefined. Normally the odds of this happening would be incredibly low, but my changes had the browser action icon being changed before the extension had finished starting up. The request for it had to go through Backloader, but it wasn't ready for requests yet. And somehow I missed that. The case for release candidates.

Posting this anyway for two reasons:
- Your edification.
- Confession that I violated semantic versioning and changed the commit v0.2.0 is based on. Seriously, who would have downloaded it in that time? :fearful: Oh good, [only 1 unique visitors today.](https://github.com/Nateowami/Backloader/graphs/traffic) History has been rewritten!

P.S. Testing of the new release would be nice. I'm now using it.

**Comment by JoshTheDerf** [comment]
Huh, good to know, that's odd. (Also, how did I not see this for three days? I have an RSS feed on your activity.)

**Comment by Nateowami** [comment]
No idea. And I have an RSS feed on you too BTW.

**Comment by JoshTheDerf** [comment]
Great. We can both be creepy. :3
