### ISSUE TITLE
Separation of default filters from user filters

### ISSUE THREAD

**Issue by Nateowami** [Nateowami/Backloader#2]
This is for discussion about how we're going to separate filters so Backloader can update with new default filters without messing up the user's filters.

**Comment by JoshTheDerf** [comment]
To Discuss:
- List storage and transmission format.
- Locking (disabling editing of) lists.
- Updating lists.
- List priorities.
- Allow multiple custom lists or not.
- UI design.

(And probably lots more.)

**Comment by Nateowami** [comment]
- That's the big one. Probably hard-code default list, and load it into local storage.
- I think locking it is the most logical solution, and I don't think that would be difficult.
- They can just be hard-coded and come with updates of Backloader. Not the most sophisticated, but I don't think it will cause problems.
- User's list first, default second. If/when multiple list are allowed, allow them to be ordered as well. Not something that needs to be done now though.
- Time will tell.
- Seems straight forward to me. Or else just guess, test, revise.

**Comment by Nateowami** [comment]
One more thing. It would be a good idea to try to keep a separation of concerns, just in case this ever gets ported to e.g. Firefox. In other words, it would be great if background logic and the interfaces with the UI and browser could be abstracted a bit (a little harder to abstract away from the browser, so don't worry much about that one).

**Comment by JoshTheDerf** [comment]
@Nateowami Alright, sounds good.
Additionally though, one might want to disable the default lists without disabling the user lists.

**Comment by Nateowami** [comment]
Definitely. And disabling the user list without disabling the default list. But there should still be a master switch so most people don't have to mess with that.

Hard coding the default list as JSON and then parsing with `JSON.parse()` would be nice, though there's not really any harm in using `defaultList = [<values here>]`.

**Comment by JoshTheDerf** [comment]
@Nateowami Alright, I might draw a wireframe of the UI for discussion then. Depends on how much free time I'll have today.

EDIT: Done. How close is this to what you're looking for?
Default page. Default List cannot be edited.
![image](https://cloud.githubusercontent.com/assets/5861371/7176576/18898534-e452-11e4-80fc-0162526f7e4a.png)
Default page with list select open. User List 1 can be edited.
![image](https://cloud.githubusercontent.com/assets/5861371/7176585/2478c9cc-e452-11e4-978c-bb1a58b73c1f.png)
Adding/Editing a list.
![image](https://cloud.githubusercontent.com/assets/5861371/7176587/28279d6e-e452-11e4-8913-39585bbecb02.png)

Also, it might end up being more advantageous to set up some sort of master server for clients to fetch list updates from, as I don't see us updating this extension much after the basic feature set is implemented. Then again, with such a small userbase, there's not really a reason to even bother with that.

EDIT: And perhaps default/predefined lists should be editable, but will always reset on updates and have a reset button provided.

**Comment by Nateowami** [comment]
_Just saw the above as edits don't get put into the RSS queue._

Can you think of a use case where a user would want to edit the default list and expect it to rest on update? I think that would just be a big pain, and would mean you have to throw a million warning signs at users.

I don't think having multiple user-defined filter lists is that necessary, so it could be put off, but if you want to do it that's great. 

Exporting lists would be a good idea, because most users with multiple machines (or OS user accounts) are going to want the same filters on all of them. Bonus: if users want to edit the default list, they can export it, import it, and then edit to their heart's content. And they could disable the default list if they wanted.

As for updating lists, I'd thought of both ways, and pretty much decided to go with hard-coding it for now. I don't think they'll need to be updated that often, but we could eventually host a versioned-list on GitHub pages, or (if for some reason that wouldn't work well) I could host a mirror on our VPS server.

How long did #1 take you? It took me over two hours to read and understand it! :scream_cat:

**Comment by JoshTheDerf** [comment]
Yeah, let's forget about editing the default lists for now. That would be lots of pain, little gain.

Multiple user-defined lists shouldn't be too hard to implement, if we already have to do list switching anyways, and would allow switching between lists or sites, or even in the future having specific lists for specific sites.

Good point on exporting lists. Shouldn't have to be more than a JSON.stringify() dump.

As for #1, it probably took so long to understand because it took about that long to write. Perhaps a little less. I was rushing really hard to get it done before our guests arrived (and it's now installed on their computers and working properly). x]

EDIT: You might want to be aware that reinstalling an extension causes the localstorage to reset, so one must take care to update properly if they want to keep their filter lists.

**Comment by Nateowami** [comment]
Just when it gets reinstalled, or when it gets updated? I can sign updates with a `.pem` file, so hopefully it shouldn't be much of a problem. And import/export of filters should further ameliorate the issue.

Don't know if it's related, but there's this in README.md:

> Fix bug whereby blocked-count (and possibly redirect-count) sometimes become undefined

I'm not sure if that's correct/still happening, but I've noticed the numbers never get very high, and sometimes it seems to reset. I've never figured out why.

**Comment by JoshTheDerf** [comment]
@Nateowami Yeah, I was wondering when/why that happened.

Just when it gets reinstalled, as far as I can tell.

**Comment by Nateowami** [comment]
A couple UI things I've thought of:
- Adding a filter should add it just below the current one.
- Currently, to move a filter from the middle to the top, you have to keep chasing the buttons up the list. I think the convention is to use just two buttons, and use them to move the selected element. They could disappear when no element is selected. Not sure exactly where they should be though. Perhaps sitting beside the list selection menu?
- Not sure if this is a good idea or not, but there should be plenty of screen space if we want to add a third column on the left for editing lists. Then you could do away with the popup, and the UI would be a bit more consistent. Adding or removing a list would have to be a bit different than adding a filter, but it could be more or less the same. Like I said, not sure about this idea.

Feel free to merge #1 at any time. I can't really contribute until then, because of the magnitude of the changes. :smile:

Oh, and as for the "bug" with the "apply" button, I think something really is wrong, because I see the disabled state, but then it partially switches back to the normal state, but the bottom border stays the same. Is that really intentional? To reproduce: click it, move mouse off, wait one second, observe darker border after color has normalized.

**Comment by JoshTheDerf** [comment]
Probably a good idea with the insertion position.
Not sure about the moving of the lists, that idea would probably work, but I'm not sure if we'lI have enough room.
I think editing a list is a rare enough event that it shouldn't need an always-visible list. However, I didn't make provision for enabling and disabling lists.

I'm planning to rewrite #1 and clean it a bit. A bit busy at the moment.

@Nateowami Ha ha, that's still not a bug. That's the focused element. Clicking another button will have the same result. (Actually, it won't. Apply is the only button that doesn't get re-created after being clicked.)

**Comment by Nateowami** [comment]
@Tribex OK, I get it, I get it. But no, clicking another one will not have the same result. :) They get regenerated so they lose focus. But I can see this in the enable/disable button in the popup.

For the filters, we need to make sure we don't redirect http to https (in general), because it can violate the content security policy, and the browser will refuse to load it (I experienced this today and switched back to v0.1.0). And that brings us to a new thought...

How about matching domains (e.g. `google.com` will match all URLs that have that as the domain)? That would simplify the protocol and wildcard stuff. And if it doesn't begin with a protocol, match all protocols. If the redirect URL specifies a protocol, use it. If not, use the request protocol.

| Request URL | Match URL | Destination URL | Final URL |
| --- | --- | --- | --- |
| https://google.com/?q=search+query | google.com | myothersearchengine.net | https://myothersearchengine.net/?q=search+query |
| http://fonts.googleapis.com/some_font | fonts.googleapis.com | fonts.useso.com | http://fonts.useso.com/some_font |
| https://fastly.net/comp/file.js | https://fastly.net | http://fastly.net | http://fastly.net/comp/file.js |
| https://sub.facebook.com/somewhere | *facebook.com | none | none |

This would eliminate the protocol issue (if the protocol isn't important, drop it), and I don't think it would be that hard to implement. Bonus: it would justify the use of the URL parser. :smile_cat:

Thoughts? Maybe that's just a bad idea.

Here's my mockup:
![raster-105218](https://cloud.githubusercontent.com/assets/6140710/7198888/af7ef4bc-e522-11e4-9218-347a8b69797b.png)
Not all of the wording and buttons are exactly right; this is just a quick 'n' dirty. Layout is the main idea.
What tool did you use?

**Comment by JoshTheDerf** [comment]
@Nateowami Yeah, the http/https thing is annoying, but in Chrome you just have to click a couple more buttons. I have to do that on discuss.atom.io, because of fastly. I think if it still fixes the problem, even if it's less convenient it's still worth it.

The other issue is that I'm pretty sure (?) that redirected requests still get passed through the extension, which could easily cause an infinite loop with your solution. https://fastly.net/comp/somefile.js -> http://fastly.net/comp/somefile.js - > http://fastly.net/comp/somefile.js etc. Otherwise your solution is solid, though it might be a bit over-complicated.

I think I see what you're heading for with the UI, nice mockup! (Though that font deserves to die a horrible death. :P )

I used Inkscape, I assume you did as well?

I'm still trying to get myself to work on this. A bit too scatterbrained at the moment.

**Comment by Nateowami** [comment]
OK, I just don't know how to do that manually. The only time http should be redirected to https is when it specifically needs to be. The problem I had was with the `http://fonts.googleapis.com/*` --> `http://fonts.useso.com/*` filter, for the request `https://fonts.googleapis.com/css?family=Open+Sans:400,400italic,700,700italic&subset=latin,greek`, because the page was loaded with https, but the resource got redirected to http. If we were simply allowed to drop the protocol, that would be a simple fix. And I think recursive redirects (though I'm not sure they would happen anyway... really don't know) could easily be patched by not redirecting from a URL to itself.

I didn't think of Inkscape (doh!), so I used Evolus Pencil. As for Comic Sans MS... not at all surprised; it gets more hate mail than any other font. I used it because it was the default, and _it fits the sketchy style_. I think that's its rightful use case: comics, mockups, and the likes. Most other fonts look out of place there. Better not make me report you for being fontist. :smile:

**Comment by JoshTheDerf** [comment]
The problem is, useso doesn't have https, so you have to force the http version. I don't know if it's possible to drop the protocol.  (I doubt it is)

Evolus Pencil actually looks quite nice, do you have a deb package or know of a mirror other than google?
Fontist and proud of it.

**Comment by Nateowami** [comment]
We've been using Linode for a VPN. Finally decided to just do it and split the cost with T&J. Want me to email it (or anything else) (about 4 MB)?

**Comment by JoshTheDerf** [comment]
Sure, feel free to e-mail it. :D

**Comment by JoshTheDerf** [comment]
Beginning initial work on this. Yeah. It took a long time to get started.

I'm rewriting the options page largely from scratch.

**Comment by Nateowami** [comment]
Great, thanks. You could consider using HTML5's `data-*` parameters for keeping track of the id of the filters, rather than parsing names. A bit simpler and easier to maintain.

**Comment by JoshTheDerf** [comment]
@Nateowami That would be nice, but PhotonUI doesn't have a way to access the raw elements yet.
Also I went outside. Haven't gotten much done so far. >_>

(I've spent a record amount of time outside this week. Phew.)

**Comment by JoshTheDerf** [comment]
I've gotten a good bit done, and should've finished mid-yesterday, but instead I played around with the new ES6 classes and object-related features all day.

Also I feel like using ES6 for everything now.

EDIT: For the record, this is going to take longer just because of a stupid issue with list re-ordering in the editing window (adding works fine). I cannot for the life of me de-duplicate entries properly when moving them around, and every idea which should work isn't working due to random limitations in built-in functions.

**Comment by Nateowami** [comment]
I think we've fully discussed this; closing now.
