### ISSUE TITLE
Improvements creating and editing rules

### ISSUE THREAD

**Issue by Nateowami** [Nateowami/Backloader#5]
When creating a new rule...
- [x] The height of the rule should be the same as the others, even though it's empty.
- [x] The first text field should be focused.
- [x] Should say that leaving destination blank blocks requests.
- [x] Clicking apply should not hide the rule-editing pane.
- [x] If no rules, should say No rules, click "Add Rule."
- [x] Pressing enter should apply rules.
- [x] Remove rule should be disabled if there are no rules or no rule is selected.
- [x] Move-up and move-down buttons disable when the selected filter is moved all the way to the top or bottom, but don't re-enable when another filter is selected.
- [x] Shouldn't be possible to edit values of locked rules.

**Comment by JoshTheDerf** [comment]
I'm not in a hurry to work on these, might get around to it if I have a ton of free time, but none of them are critical issues.

**Comment by Nateowami** [comment]
Yeah, most of these are trivial. I'll probably do a few of these pretty soon; just wanted to put these up so they'd be somewhere.

**Comment by Nateowami** [comment]
Wow. PhotonUI is _hard_. I've tried 
- Clicking apply should not hide the rule-editing pane.
- If no rules, should say No rules, click "Add Rule."
- Pressing enter should apply rules.

and got stuck on all of them!

**Comment by JoshTheDerf** [comment]
Indeed. It's not very good for dynamic usage, which is kind of annoying.

**Comment by JoshTheDerf** [comment]
Yippie. :D
