### ISSUE TITLE
Minor bugs creating lists

### ISSUE THREAD

**Issue by Nateowami** [Nateowami/Backloader#6]
When creating a new list...
- [x] First text field should be focused. And empty.
- [x] Editing the name should immediately update the name shown in the position of lists.
- [x] Clicking cancel should not leave "New list" as the current list.

**Comment by Nateowami** [comment]
@Tribex Any idea how to programatically change what's selected in a PhotonUI select menu? This has stumped me. Might not be possible. Maybe just use a + button? Or do you think that's not a good idea? Not a lot of room in the top row, but it could be squeezed, and the right pane is already pretty spacious.

**Comment by Nateowami** [comment]
If you know a better way to focus a text field than this, let me know. Kinda hackish, but I don't see anything in the PhotonUI docs.

``` javascript
p.getWidget("new-list-name").addClass("new-list-name");
$(".new-list-name").focus();
```

Works for now.

**Comment by JoshTheDerf** [comment]
@Nateowami For changing the selection, change the value, I believe. See https://github.com/Nateowami/Backloader/blob/master/pages/options/options.js#L118-L120

Not sure about focusing, that's probably the best way to do it, for now.

To by honest, I'm not really using PhotonUI anymore. Despite liking that style of programming, it gets really muddy fast. (Thanks for the reminder though, I still need to finish the wave theme.)

**Comment by Nateowami** [comment]
Ah, OK, thanks. I thought writing to the value wouldn't have any 
immediate effect. Not sure how they would have implemented that.

**Comment by JoshTheDerf** [comment]
Keep in mind you have to set the value to null first. :)

**Comment by Nateowami** [comment]
Completed in 86e4b14ef89219659505212b903b240e4b725226. Not sure if there's a better way to explain "active page," so I've removed that from this issue. Closing now.

**Comment by JoshTheDerf** [comment]
Excellent! :D
