### ISSUE TITLE
Backloader automatically enabled on startup

### ISSUE THREAD

**Issue by Nateowami** [Nateowami/Backloader#9]
Although the enable/disable toggle remembers state after a restart of Chrome, Backloader always is enabled on startup.

**Comment by JoshTheDerf** [comment]
@Nateowami That's weird. You're saying the extensions keeps blocking requests even when the toggle is disabled, after Chrome has been started?

**Comment by Nateowami** [comment]
@Tribex Yes. Probably just a tiny bug.

**Comment by JoshTheDerf** [comment]
@Nateowami I'll check on it later.

EDIT: Should be fixed by #10
